version: '3'

services:

  platform_incoming_api:
    build: ./platform_in/
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./platform_in/:/project/
    ports:
      - 5000:5000
    env_file:
      - config.env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig   
    depends_on:   
      - redis
        
  worker:
    build: ./platform_in/
    command: python manage.py run_worker
    env_file:
        - config.env
    environment:
        - FLASK_ENV=development
        - APP_SETTINGS=app.config.DevelopmentConfig
    volumes:
        - ./platform_in/:/project/
    depends_on:  
      - redis
        
  redis:
        image: redis:5.0.7-alpine
